In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,9,6,2,8,1])

In [3]:
arr2-arr1

array([ 3,  7,  3, -2,  3, -5])

In [4]:
arr1*arr2

array([ 4, 18, 18,  8, 40,  6])

In [5]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [7]:
arr2>3
#compare the each element of the arr2 with the 3 and returns boolean data

array([ True,  True,  True, False,  True, False])

In [27]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [28]:
arr3.dot(arr4)
# matrix multiplication of arr3 and arr4:

array([[ 28,  31],
       [100, 112]])

In [29]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
print(f'the max element of arr3 is: {arr3.max()} and the minimum element of the arr3 is:{arr3.min()}')

the max element of arr3 is: 5 and the minimum element of the arr3 is:0


In [31]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
column_wise_min = arr4.min(axis=0)
column_wise_min

array([6, 7])

In [43]:
arr4.min(axis=1)
# row wise min list :

array([ 6,  8, 10])

In [56]:
arr4.max(axis=0)
# column wise max element list 

array([10, 11])

In [57]:
arr4.max(axis=1)
#  row wise maximum in list :

array([ 7,  9, 11])

In [46]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [58]:
sum_of_all_elemen = arr4.sum()
sum_of_all_element

51

In [59]:
column_wise_sum = arr4.sum(axis=0)
column_wise_sum

array([24, 27])

In [61]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
row_wise_sum = arr4.sum(axis=1)
row_wise_sum

array([13, 17, 21])

In [65]:
print("the mean of the all element of the array is:")
arr4.mean()

the mean of the all element of the array is:


8.5

In [67]:
print("the standard deviation: below ")
arr4.std()

the standard deviation: below 


1.707825127659933

In [69]:
print("the sin of the matrix is:")
np.sin(arr4)

the sin of the matrix is:


array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [72]:
np.median(arr4)
print(f"the median of the array is: {np.median(arr4)}")

the median of the array is: 8.5


In [76]:
print('the exponent value of the array is:')
np.exp(arr4)

the exponent value of the array is:


array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])