In [10]:
# to check the shape of the arr1
arr1.shape

(2, 4)

In [8]:
arr2 = np.array([[[1, 2], [12, 34]], [[11, 22], [55, 66]]])
print(arr2)

[[[ 1  2]
  [12 34]]

 [[11 22]
  [55 66]]]


In [2]:
# properties of the numpy array:
import numpy as np
arr1 = np.array([[1,2,3,4],[12,34,32,54]])
arr1

array([[ 1,  2,  3,  4],
       [12, 34, 32, 54]])

In [9]:
# to check the shape of the arr2:
arr2.shape

(2, 2, 2)

In [11]:
# to check the dimension of the arr2 matrix:
arr2.ndim

3

In [12]:
# to check the dimension of the arr1 matrix above:
arr1.ndim

2

In [17]:
arr3 = np.array([[1,2,3],[33,44,55]])
# to check the dimension of the array:
print(f"the dimension of the arr3 is:{arr3.ndim} ")
# to check the size of the array:
print(f"the size of the arr3 is:{arr3.size}")

the dimension of the arr3 is:2 
the size of the arr3 is:6


In [29]:
arr4 = np.array([[[1, 2], [12, 34]], [[11, 22], [55, 66]]])
print("the matix form of the arr4 is shown below:")
print(arr4)
print(f'the dimension of the arr4 is:{arr4.ndim} ')
print(f"the no of element in the arr4 is:{arr4.size}")
print(f"the size of each element in bytes :{arr4.itemsize}")


the matix form of the arr4 is shown below:
[[[ 1  2]
  [12 34]]

 [[11 22]
  [55 66]]]
the dimension of the arr4 is:3 
the no of element in the arr4 is:8
the size of each element in bytes :4


In [27]:
arr5 = np.array([1,2,3,4,5])
# Print the result
print(f"Size of each element in bytes: {arr5.itemsize}")

Size of each element in bytes: 4


In [41]:
print(f"Data type of arr5: {arr5.dtype}")

Data type of arr6: int32 which indicates that each element in the array is a 32-bit integer.


In [38]:
print(f"The data type of arr5 is: {arr5.dtype}.")


the data type of arr7 is:float64 which indicates each element in the array is a 64-bit float.
