In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1.astype('float')

array([1., 2., 3.])

In [4]:
arr1.astype('int')

array([1, 2, 3])

In [14]:
# indexing,sclicing and Iteration:
arr12 = np.arange(24).reshape(2,12)
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [16]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
arr12[:3] #row sclicing-> from the index o to 2 of the row:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [25]:
arr1[1:4]

array([2, 3, 4])

In [29]:
arr12 = arr12.reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
# for extracting the row array/matrix:
arr12[5]

array([20, 21, 22, 23])

In [67]:
# for extracting the row of the array from the 0 to 2 index:
arr12[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
# for the extracting the first column of the array/ matrix:
arr12[:,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

In [69]:
# for extracting the column of the matrix form the 2nd to fourth column :
arr12[:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [70]:
# for extracting the row and column of the matrix or array:
arr12[:2,:2]

array([[0, 1],
       [4, 5]])

In [71]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
# i want the result like: [[10,11],
#                          [14,15]]
arr12[2:4,2:4] #[row,column]

array([[10, 11],
       [14, 15]])

In [73]:
# for [[17,18,19]
#      [21,22,23]]
arr12[4:6,1:4] # [row_sclicing, column_sclicing]

array([[17, 18, 19],
       [21, 22, 23]])

In [76]:
# iteration in numpy:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
for i in arr12:
    print(i)
# this prints the each row of the element of the array in the list format .

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [80]:
for i in np.nditer(arr12):
    print(i)
# this code print each element from the first row and after the completion of the first then it begins the second row as it is: 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
