In [1]:
import numpy as np

In [2]:
arr4 = np.array([[6,7],[8,9],[10,11]])
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
# today we are looking the Reshaping Numpy arrays:

In [8]:
print(f"the dimension of the arr4 is:{arr4.ndim} ")

the dimension of the arr4 is:2 


In [12]:
# changing the arr4 into one dimension:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [13]:
print(f"the dimension after ravel:{arr4.ravel().ndim}")

the dimension after ravel:1


In [14]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [15]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [19]:
arr3 = np.array([[0,1,2],[3,4,5]])
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
horizontal_merge_of_array = np.hstack((arr3,arr5))
horizontal_merge_of_array

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [23]:
vertical_merge_of_array = np.vstack((arr3,arr5))
vertical_merge_of_array                           

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [24]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.vsplit(arr3,2)
# split between two matrixes of the array.

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [28]:
np.hsplit(arr3,3)
# split between the each common index's column element of the two matrix of the array.

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [29]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
np.vsplit(arr4,3)
# np.vsplit(array_name,no_of_row);

[array([[6, 7]]), array([[8, 9]]), array([[10, 11]])]

In [34]:
np.hsplit(arr4,2)
# np.hsplit(array_name,no_of_column);

[array([[ 6],
        [ 8],
        [10]]),
 array([[ 7],
        [ 9],
        [11]])]