In [4]:
import numpy as np

In [5]:
# some important numpy functions

In [6]:
np.random.random()#produces the random float values from the 0.0 to 1

0.6696377249597522

In [7]:
np.random.seed(1)
np.random.random()
# this above code gives the random constant float value between 0 and 1 .

0.417022004702574

In [8]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [9]:
np.random.uniform(1,100) #this gives the random float values from between the 1 to 100

3.566696950961242

In [10]:
arr1 = np.random.uniform(1,100,10).reshape(2,5)
# this generates the 10 random float values in the array in 1 dimension .
arr1

array([[55.41658531, 44.09691687, 42.61641241, 33.70314728, 21.26021477],
       [62.30782567, 30.66581269, 27.41590024, 62.49224944, 53.38506733]])

In [11]:
arr2 = np.random.uniform(50,100,24).reshape(6,4)
# np.random.uniform(start,end,no_of_element).reshape(row,column)
arr2

array([[56.72899727, 75.67890606, 59.22199328, 89.26675739],
       [92.69876463, 74.71184187, 92.32807427, 53.98227385],
       [75.26230451, 53.26432522, 71.40611638, 54.82654578],
       [56.35799859, 79.83726545, 61.30060003, 55.34728422],
       [61.01531035, 67.49131425, 73.38937423, 60.08716131],
       [82.02033626, 74.15349178, 75.261836  , 69.34463256]])

In [12]:
arr3 = np.random.randint(5,16,4)
# this gives the random integer value array between 5 to 16 and the number of element in the array is 4.
arr3

array([13, 15, 10, 14])

In [13]:
np.random.randint(1,10,15).reshape(3,5)

array([[4, 1, 1, 3, 9],
       [9, 3, 7, 6, 7],
       [7, 7, 4, 9, 3]])

In [14]:
a = np.random.randint(1,10,6)
a #gives the random integer value between 1 to 10 and the no of element in the array is 6.

array([2, 5, 9, 2, 7, 6])

In [15]:
a.max()#this gives the maximum element in the array a .

9

In [16]:
np.min(a)
# this gives minimum value in the array a .

2

In [17]:
a1 = np.array([1,4,3,5,2,7,9,8])
a1

array([1, 4, 3, 5, 2, 7, 9, 8])

In [18]:
np.argmax(a1) #this gives the index of the array which has maximum element.

6

In [19]:
np.argmin(a1) #this gives the index of the array which has minimum element in the array a1

0

In [20]:
a1

array([1, 4, 3, 5, 2, 7, 9, 8])

In [21]:
minimum_element = a1[np.argmin(a1)]
minimum_element

1

In [22]:
largest_element = a1[np.argmax(a1)]
largest_element

9

In [23]:
a = np.random.randint(1,10,6)
a

array([2, 3, 5, 8, 7, 5])

In [24]:
a[a%2==0]=-1
a
# this changes the even number into -1 in the array a.

array([-1,  3,  5, -1,  7,  5])

In [25]:
a = np.random.randint(1,50,6)
a

array([38, 11,  9, 27, 36, 28])

In [28]:
print(a)
np.where(a%2==1,-1,a) #here if number not found even then it is replaced by -1.

[38 11  9 27 36 28]


array([38, -1, -1, -1, 36, 28])

In [35]:
arr1 = np.random.randint(1,25,24).reshape(4,6)
arr1

array([[ 5, 12, 15, 19, 10,  8],
       [18, 19,  2, 16, 15,  1],
       [ 8, 18,  9, 13, 15, 10],
       [12, 15, 15,  1, 24, 17]])

In [37]:
np.sort(arr1)#this sorted data of each row in the ascending order.

array([[ 5,  8, 10, 12, 15, 19],
       [ 1,  2, 15, 16, 18, 19],
       [ 8,  9, 10, 13, 15, 18],
       [ 1, 12, 15, 15, 17, 24]])

In [39]:
arr2 = np.random.randint(1,50,14)
arr2

array([ 2, 44,  6,  8, 17, 42, 29, 16, 18, 38, 32, 35, 17, 43])

In [40]:
sorted_array = np.sort(arr2)
sorted_array

array([ 2,  6,  8, 16, 17, 17, 18, 29, 32, 35, 38, 42, 43, 44])

In [43]:
print(sorted_array)
np.percentile(sorted_array,25)
# np.percentile(sorted_array, 25). This means that 25% of the values in the sorted array are less than or equal to the calculated percentile.

[ 2  6  8 16 17 17 18 29 32 35 38 42 43 44]


16.25

In [50]:
random_array = np.random.randint(1,101, size = 20)
print("random Array ",random_array)
percentile_25 = np.percentile(random_array, 25)
print(percentile_25)

random Array  [ 62  99  24  20  98  32  82  90  74  60   1   9  11   9 100  47  36  79
  80  55]
23.0


In [51]:
 # the 25th percentile is approximately 23.0. This means that 25% of the values in the randomly generated array are less than or equal to 23.0. The 25th percentile is a measure of central tendency that helps describe the distribution of the data.